all:
  children:

    routers:
      children:
        arista:
          hosts:
            R1:
              ansible_host: 10.200.0.1
            R2:
              ansible_host: 10.200.0.2
            R4:
              ansible_host: 10.200.0.4
            R6:
              ansible_host: 10.200.0.6
            R9:
              ansible_host: 10.200.0.9
        vyos:
          hosts:
            ISP:
              ansible_host: 10.200.0.10
            R3:
              ansible_host: 10.200.0.3
            R5:
              ansible_host: 10.200.0.5
            R7:
              ansible_host: 10.200.0.7
            R8:
              ansible_host: 10.200.0.8

    AS_numbers:
      children:
        AS_23:
          hosts:
            R2:
            R3:
        AS_4567:
          hosts:
            R4:
            R5:
            R6:
            R7:
